version: '2'
services:
  api:
    build:
      context: ./dockerfile/api
    command: ruby api.rb
    volumes:
      - .:/site-generator
    ports:
      - "4567:4567"
  web:
    build:
      context: ./dockerfile/web
    volumes:
      - ./public-html:/usr/local/apache2/htdocs
    ports:
      - "80:80"
